### PR TITLE
Added support for python3

### PR DESCRIPTION
**Pull request by Baschdl**
Made the code python 2 and 3 compatible

### CODE REVIEW

**Comment by mniehe** [comment]
Need this feature as well

**Comment by jarus** [comment]
I agree sqlalchemy-hana should have support for Python 3 but it should still work with Python 2.7. I think the string casts will break the support of unicode schema and table names in Python 2.7. Also please adjust the commit message of 74c9eb9.

**Comment by michaelkuty** [comment]
Yes, I think that you should use six for python2 and python3 compat instead switching unicode to string.

**Comment by Baschdl** [comment]
@drs-m Could you please adjust the commit message of 74c9eb9?

**Comment by jarus** [comment]
Version 0.3.0 of sqlalchemy-hana should be the first version with Python 3 support. I committed already a first working version de2e794531380d0a62d778cb48dcda1ff776fcec. It would be great if you could test the version and provide some feedback in a new issues.

**Pull request closed without merging**
